"""nusacrowd zero-shot prompt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ru8DyS2ALWfRdkjOPHj-KNjw6Pfa44Nd
"""
import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), "src"))

import csv
from os.path import exists
import glob
import random

import numpy as np
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import f1_score, accuracy_score, classification_report

import torch
import torch.nn.functional as F
import datasets

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, AutoModelForCausalLM

from dataset_utils import load_dataset
from indexer import SimpleDatasetIndexer
from prompter import ICLPrompter, ITCPrompter
from classifier import predict_classification_batch

DEBUG=False

lang_map = {
    'btk': 'Batak', 'sun': 'Sundanese', 'jav': 'Javanese', 
    'mad': 'Madurese', 'mak': 'Buginese', 'min': 'Minangkabau',
    'amh': 'Amharic', 'hau': 'Hausa', 'ibo': 'Igbo', 'lug': 'Luganda', 'pcm': 'Nigerian Pidgin',
    'sna': 'chShona', 'swa': 'Kiswahili', 'xho': 'isiXhosa', 'yor': 'Yorùbá',
    'aym': 'Aymara', 'bzd': 'Bribri', 'cni': 'Asháninka', 'gn': 'Guaraní', 'hch': 'Wixarika',
    'nah': 'Nahuatl', 'oto': 'Otomí', 'quy': 'Quechua', 'shp': 'Shipibo-Konibo', 'tar': 'Rarámuri',
    'ind': 'Indonesian', 'eng': 'English', 'spa': 'Spanish', 'arb': 'Arabic', 'fra': 'French', 
    'deu': 'German', 'hin': 'Hindi', 'ita': 'Italian', 'por': 'Portuguese'
}

dataset_to_metadata_map = {
    # key: (prompt_template, icl_template, iia_template, icl_keys, iia_keys, x_iia_keys)
    'americasnli-spa': (
        'Predice la etiqueta de implicación del siguiente par de oraciones:\n{context}\n{query}',
        'Premisa: "{premise}"; Hipótesis: "{hypothesis}" => {label}',
        '{premise_1} => {premise_2}\n{hypothesis_1} => {hypothesis_2}',
        ['premise', 'hypothesis'], ['premise_1', 'hypothesis_1'], ['premise_2', 'hypothesis_2']
    ),
    'americasnli': (
        'Predict the entailment label of the following pair of sentences:\n{context}\n{query}',
        'Premise: "{premise}"; Hypothesis: "{hypothesis}" => {label}',
        '{premise_1} => {premise_2}\n{hypothesis_1} => {hypothesis_2}',
        ['premise', 'hypothesis'], ['premise_1', 'hypothesis_1'], ['premise_2', 'hypothesis_2']
    ),
    'nusatranslation-ind': (
        'Prediksikan label sentimen dari kalimat berikut:\n{context}\n{query}',
        '{text} => {label}',
        '{text_1} => {text_2}',
        'text', 'text_1', 'text_2'
    ),    
    'nusatranslation': (
        'Predict the sentiment label of the following sentence:\n{context}\n{query}',
        '{text} => {label}',
        '{text_1} => {text_2}',
        'text', 'text_1', 'text_2'
    ),
    'masakhanews': (
        'Predict the topic of the following news title:\n{context}\n{query}',
        '{text} => {label}',
        '{text_1} => {text_2}',
        'text', 'text_1', 'text_2'
    ),
    'tweetsentimulti': (
        'Predict the sentiment label of the following tweet:\n{context}\n{query}',
        '{text} => {label}',
        '{text_1} => {text_2}',
        'text', 'text_1', 'text_2'
    ),
}

def generate_input_label(prompts, labels):
    inputs = []
    for label, prompt in zip(labels, prompts):
        inputs.append(prompt.replace('[LABELS_CHOICE]', label))
    return inputs

if __name__ == '__main__':
    if len(sys.argv) < 2:
        raise ValueError('main_itc_alignment.py <model_path_or_name> <dataset_name> <itc_type> <itc_index_type> <itc_num_exemplar> <label_type> <batch_size>')

    BASE_PATH='./dataset'
    MODEL = sys.argv[1]
    DATASET_NAME = sys.argv[2] # americasnli, nusatranslation, masakhanews
    ITC_TYPE = sys.argv[3] # cross, mono, none
    ITC_INDEX_TYPE = sys.argv[4].split(',') # random, count, tf-idf, sbert
    ITC_EXEMPLAR_COUNT = int(sys.argv[5])
    LABEL_TYPE = sys.argv[6]
    BATCH_SIZE = int(sys.argv[7])

    # Load Dataset
    eval_dsets, icl_dsets, xicl_lang, iia_dsets, itc_dsets, ioa_df = load_dataset(dataset=DATASET_NAME, base_path=BASE_PATH)
    
    metrics = {
        'dataset': [], 'lang': [],
        'accuracy': [], 'macro_f1': [], 'weighted_f1': []
    }
    
    print('MODEL', MODEL)
    print('DATASET_NAME', DATASET_NAME)
    print('ITC_TYPE', ITC_TYPE)
    print('ITC_INDEX_TYPE', ITC_INDEX_TYPE)
    print('ITC_EXEMPLAR_COUNT', ITC_EXEMPLAR_COUNT)
    print('LABEL_TYPE', LABEL_TYPE)
    print('BATCH_SIZE', BATCH_SIZE)
    print()

    for dset_lang, eval_dset in eval_dsets.items():
        if dset_lang == 'eng':
            continue
        if LABEL_TYPE == 'Target' and dset_lang not in ioa_df.index:
            continue

        print(f'== {DATASET_NAME} {dset_lang} ==')

        ###
        # Preprocessing
        ###

        # Extract Metadata
        prompt_template, icl_template, iia_template, icl_keys, iia_keys, x_iia_keys = dataset_to_metadata_map[DATASET_NAME]
        
        # Prepare Prompter
        query_keys = icl_keys if type(icl_keys) == list else [icl_keys]
        src_keys = x_iia_keys if type(x_iia_keys) == list else [x_iia_keys]
        tgt_keys = iia_keys if type(iia_keys) == list else [iia_keys]
        itc_prompter = ITCPrompter(
            headers = [ # Target Inputs
                f'{lang_map[dset_lang]} {key.split("_")[0].capitalize()}' for key in tgt_keys
            ] + [ # Label
                f'Label'
                # f'{lang_map[dset_lang]} Label' if LABEL_TYPE == 'Target' else f'{lang_map[xicl_lang]} Label'
            ] + ([ # Source Inputs
                f'{lang_map[xicl_lang]} {key.split("_")[0].capitalize()}' for key in src_keys
            ] if ITC_TYPE in ['cross', 'mono-trans'] else []),
            target_keys=tgt_keys, label_keys=['label'], 
            source_keys=src_keys if ITC_TYPE in ['cross', 'mono-trans'] else [], 
            query_keys=query_keys
        )

        # Retrieve & preprocess labels
        label_names = list(set(eval_dset['label']))
        if LABEL_TYPE == 'Target':
            label_map = ioa_df.loc[dset_lang, 'label_map']
        else:
            label_map = None
        
        ###
        # Indexing
        ###
        if ITC_TYPE == 'cross':
            itc_dset = itc_dsets[dset_lang]    
            itc_indexer = SimpleDatasetIndexer(dataset=itc_dset, index_key=x_iia_keys, index_type=ITC_INDEX_TYPE)
        elif ITC_TYPE in ['mono', 'mono-trans']:
            itc_dset = itc_dsets[dset_lang]    
            itc_indexer = SimpleDatasetIndexer(dataset=itc_dset, index_key=iia_keys, index_type=ITC_INDEX_TYPE)
        else:
            itc_dset = None
            itc_indexer = None
            
        ###
        # Inference
        ###
            
        inputs, preds, golds = [], [], []

        # Perform Inference
        prompts, labels = [], []
        for e, sample in enumerate(eval_dset):
            if e < len(preds):
                continue

            if type(icl_keys) == str:
                input_query = sample[icl_keys]
            else: # type(icl_keys) == list
                input_query = [sample[key] for key in icl_keys]
            label = sample['label']

            ###
            # Retrieve Exemplars
            ###

            # Retrieve ITC Exemplars
            if itc_indexer is not None:
                itc_samples = itc_indexer.get_similar_samples(input_query, n_samples=ITC_EXEMPLAR_COUNT)
                if LABEL_TYPE == 'Target':
                    itc_samples['label'] = [label_map[label] for label in itc_samples['label']]
            else:
                itc_samples = None

            ###
            # Prepare Zero-Shot / Few-Shot Prompt Text
            ###
            prompt_text = itc_prompter.generate_prompt(
                input_exemplar=sample,
                exemplars=itc_samples
            )

            prompts.append(prompt_text)
            labels.append(label)

            ###
            # Perform zero-shot / few-shot Inference
            ###

            # Batch Inference
            if len(prompts) == BATCH_SIZE:
                if LABEL_TYPE in ['True', 'Target']:
                    # Map label names from original label to target language label using label_map
                    ioa_labels = [label_map[label] for label in labels]
                    inputs = generate_input_label(prompts, ioa_labels)
                else:
                    inputs = generate_input_label(prompts, labels)

                for text_input in inputs:
                    print(text_input)
                    print('============')
                prompts, labels = [], [] 
                break
